### ISSUE TITLE
Plugin "Board" zeigt error-Meldung an

### ISSUE THREAD

**Issue by nelkasovic** [nelkasovic/lehr-bar.ch#1]
![Image](https://user-images.githubusercontent.com/106140818/241267266-dd538515-3727-4571-872a-89e4bade75b4.png)

https://lehr-bar.ch/mod/board/view.php?id=936

**Comment by NinaKatja** [comment]
![Image](https://github.com/nelkasovic/lehr-bar.ch/assets/134771252/ae25500c-8b7e-4d38-831a-c36cd64a2647)

formsubmissioninvalid
error/formsubmissioninvalid
Datei: /mod/board/external.php
Zeile: 349
Stack trace:

Error code: formsubmissioninvalid
$a contents: 
* line 349 of /mod/board/external.php: moodle_exception thrown
* line 261 of /lib/externallib.php: call to mod_board_external::submit_form()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()

**Comment by nelkasovic** [comment]
@NinaKatja Es scheint ein bekannter aber noch nicht gelöster Bug zu sein. Dies gemäss Diskussion im Git-Forum des Entwicklers:

- https://github.com/brickfield/moodle-mod_board/issues/71
- https://github.com/brickfield/moodle-mod_board/issues/50

Ich schätze mal, dass wir nichts machen können, wenn auch die Teilnehmenden keine Einträge erfassen können.

**Comment by NinaKatja** [comment]
Das heisst, wir können es gar nicht verwenden?
Bei diesem Angebot https://lehr-bar.ch/course/view.php?id=35 haben wir zuerst mit Etherpads gearbeitet, aber bei denen sieht man je nachdem auch Fehlermeldungen und die halten sich halt nur eine bestimmte Zeit lang. Kennst du Alternativen, die wir statt Etherpad oder Board nutzen könnten?

**Comment by angelajochum** [comment]
Bitte nachrecherchieren, ob eine Lösung bereits vorhanden ist. aprendo arbeitet ja jetzt auch mit dem Board und da funktioniert ist. an der PHSG haben viele Ersteller das Board benutzt.
Besten Dank Angela

**Comment by nelkasovic** [comment]
@angelajochum 

Ja, bei aprendo sind jedoch nicht die gleichen Versionen installiert. Das was ich machen kann, ist die das Moodle in verschiedenen Versionen und dann eine passende Board-Plugin Version zu installieren. Ich kenne das Plugin nicht und arbeite auch nicht mit dem aprendo-Moodle, daher weiss ich auch nicht, ob dort Probleme damit bekannt sind. Das müsste man bei den Autoren nachfragen. 

Ich schätze den Aufwand hierfür auf max. 3 Stunden à CHF 140.-

**Comment by nelkasovic** [comment]
Zur Info, Versionsangaben:

Aprendo:
- Board Plugin: 1.311.01 (Build 2022101201)
- Moodle 1.311.01 (Build 2022101201)

LehrBar:
- Board Plugin: 1.39.06 (Build 2021101501)
- Moodle 3.10.4 (Build: 20210510)

Current versions

1.400.01 (Build 2022101201) (2022040105)
Moodle 4.0, 4.1
Released: Freitag, 25. November 2022, 00:46
[code prechecks 0 | 82](https://moodle.org/plugins/mod_board/1.400.01-build-2022101201/28019)
[Release notes](https://moodle.org/plugins/mod_board/1.400.01-build-2022101201/28019)

1.311.01 (Build 2022101201) (2021110105)
Moodle 3.11
Released: Freitag, 25. November 2022, 00:45
[Release notes](https://moodle.org/plugins/mod_board/1.311.01-build-2022101201/28018)

1.39.07 (Build 2022101201) (2021052415)
Moodle 3.9, 3.10
Released: Freitag, 25. November 2022, 00:44
[Release notes](https://moodle.org/plugins/mod_board/1.39.07-build-2022101201/28017)

**Comment by learningtechnologyservices** [comment]
Hi there,

Many thanks for reporting this issue, we are confident it has been resolved by [this commit here](https://github.com/brickfield/moodle-mod_board/commit/1737ad104f974522bd5eae3738bad3c1ee7763a0). This now correctly allocates and processes the external service parameters for submitting and retrieving posts.

Kind regards
Karen

**Comment by NinaKatja** [comment]
Lieber @nelkasovic 
Konntest du dir das schon anschauen? Heisst dass, das wir das Board nun doch benutzen können?

**Comment by nelkasovic** [comment]
@NinaKatja Ich schätze, dass wir das Problem erst dann richtig beheben können, wenn wir auf Moodle 4 umsteigen. Ich habe die Anpassung jedoch lokal eingespielt, versuch es bitte erneut zu testen. Ggf. ist das eine Abhilfe jedoch nur provisorisch.

**Comment by NinaKatja** [comment]
Leider kommt bei mir noch immer dieselbe Fehlermeldung :(
![grafik](https://github.com/nelkasovic/lehr-bar.ch/assets/134771252/80bdafd0-f0a8-4abe-a71e-98dc636ca8bd)
