### ISSUE TITLE
falsche Verlinkung führt Moodle selbstständig durch

### ISSUE THREAD

**Issue by angelajochum** [nelkasovic/lehr-bar.ch#15]
@nelkasovic : Lieber Nermin. Wir hatten dies mal ganz am Anfang unseres Austausches und da hatte ich mal berichtet, dass in dem Kurs Verlinkungen auftauchen, welche nicht manuell von den Ersteller:innen erstellt wurden, sondern automatisch von Moodle erstellt wurden. Dies möchten wir nicht. Es ist immer noch ein Problem und verwirrt viele Tester:innen.
Wie kann man dieses Problem lösen?

IST: 
![grafik](https://github.com/nelkasovic/lehr-bar.ch/assets/106140818/2f360484-6655-4dd5-b74f-2f03e5dfeac0)

![grafik](https://github.com/nelkasovic/lehr-bar.ch/assets/106140818/60947301-e42e-4207-bc3f-728222ca2b96)
Hier ist eine Verlinkung zu dem Dokument welches direkt unterhalb angeführt wird.

SOLL:

Es sollen keine automatischen Verlinkungen durch Moodle durchgeführt werden

**Comment by nelkasovic** [comment]
@angelajochum Ist eine Einstellung bzw. ein Filter. Diesen kannst du via Zahnrad->Filter steuern. Ich habe die globale Einstellung bereits deaktiviert. Es kann sein, dass dies jedoch für bereits vorhandene Kurse noch manuell eingestellt werden muss.

![CleanShot 2023-10-11 at 15 31 31](https://github.com/nelkasovic/lehr-bar.ch/assets/1759407/835cf24f-6ec8-4d8a-8e16-292f951366c5)
