### ISSUE TITLE
Thema hat einen blauen Strich auf der Seite

### ISSUE THREAD

**Issue by angelajochum** [nelkasovic/lehr-bar.ch#16]
@nelkasovic : folgendes Angebot hat einen blauen Strich, welchen ich nicht entfernt bekomme.
IST:
![grafik](https://github.com/nelkasovic/lehr-bar.ch/assets/106140818/523ab89c-7e33-4abb-8702-910f9a5ca6a2)
https://lehr-bar.ch/course/view.php?id=45

SOLL: Blauen Strich entfernen

**Comment by nelkasovic** [comment]
@angelajochum Das ist die Hervorhebung vom aktuellen Thema im Kurs, kann hier entfernt werden:

![CleanShot 2023-10-11 at 15 13 44](https://github.com/nelkasovic/lehr-bar.ch/assets/1759407/9b7a414f-d0ac-4a58-a1cf-161438cf9527)
