### ISSUE TITLE
Team-Mitglieder Fotos nicht gleich gross dargestellt

### ISSUE THREAD

**Issue by angelajochum** [nelkasovic/lehr-bar.ch#18]
IST:
![grafik](https://github.com/nelkasovic/lehr-bar.ch/assets/106140818/9a50cc06-4cd2-4b21-b01a-86ad9be0aca9)

SOLL:
Alle Bilder sollen oben und unten gleich abschliessen.

**Comment by nelkasovic** [comment]
@angelajochum Das hängt mit dem Format des Bildes zusammen. Die Formate bzw. das Seitenverhältnis soll bei allen gleich sein.

**Comment by angelajochum** [comment]
@nelkasovic: wahrscheinlich ist dies so. Luca, Kerstin, Anna, Nina und Corinne arbeiten alle bei der gleichen Institution. Und da stimmen die Bildrahmen ja irgendwie ....

**Comment by nelkasovic** [comment]
@angelajochum Muss halt vor dem Upload noch geprüft und allenfalls korrekt eingestellt werden. Ich habe die beiden nun manuell korrigiert.

**Comment by angelajochum** [comment]
@nelkasovic danke
