### ISSUE TITLE
Impressum einfügen

### ISSUE THREAD

**Issue by angelajochum** [nelkasovic/lehr-bar.ch#19]
@nelkasovic 
IST:
![grafik](https://github.com/nelkasovic/lehr-bar.ch/assets/106140818/f89609b9-7eee-4fe8-a07c-74e20a88e006)

SOLL:
Button "Alle Caches löschen" und "Laden Sie die mobile App" löschen
UND 
Verlinkung Impressum mittig unten lehr-bar.ch, gerne auch in einem solchen Kasten

**Comment by nelkasovic** [comment]
@angelajochum Impressum ist eingefügt. 
![CleanShot 2023-10-11 at 15 10 07](https://github.com/nelkasovic/lehr-bar.ch/assets/1759407/9f7d8db3-8e48-45f0-b343-86117a4aff79)

Der Link für die Mobile-App ist entfernt.

Der Link für Caches löschen ist nur für die Site-Admins sichtbar und stört nicht denke ich.
