### ISSUE TITLE
Videogrössen einheitlich

### ISSUE THREAD

**Issue by nelkasovic** [nelkasovic/lehr-bar.ch#5]
IST

SOLL

Screenshot und Beispiele oder Link

**Comment by NinaKatja** [comment]
Die Videos sind in verschiedenen Angeboten unterschiedlich gross eingebettet. Es wäre hilfreich, wenn diese alle in einer einheitlichen Grösse daherkämen oder wir wüssten, welche Grösse wir am besten einstellen sollen.
Z.B. https://lehr-bar.ch/course/view.php?id=35 vs. https://lehr-bar.ch/course/view.php?id=39

**Comment by nelkasovic** [comment]
Duplikat, Diskussion dazu https://github.com/nelkasovic/lehr-bar.ch/issues/7
