### ISSUE TITLE
Nutzung von der Aktivität Verzeichnis für Videos

### ISSUE THREAD

**Issue by angelajochum** [nelkasovic/lehr-bar.ch#6]
https://lehr-bar.ch/course/view.php?id=48#section-2

**Comment by angelajochum** [comment]
@NinaKatja: Bitte noch ausformulieren. Da ging es damals um deine Frage, dass die Videos in einem Ordner nicht erst heruntergeladen werden dürfen.

**Comment by NinaKatja** [comment]
Genau: Das Angebot weist sehr viele Videos auf, die momentan fast alle direkt in Ordnern hochgeladen wurden. Wenn man diese nun anschauen möchte, muss man die Videos herunterladen, was nicht ideal ist.
Welche Lösung gibt es, so dass die Videos über SwitchTube eingebettet werden können und vor dem Anschauen nicht heruntergeladen werden müssen, diese aber nicht eingebettet werden müssen (das Angebot würde zu lange und unübersichtlich werden). Das Ganze als Links anzugeben würde wahrscheinlich auch nicht besonders schön aussehen. Die Strukturierung in Ordnern ist eigentlich super, aber eben, wir brauchen eine Möglichkeit, dass die Dateien darin nicht direkt heruntergeladen, sondern in einem neuen Tab geöffnet werden.

**Comment by nelkasovic** [comment]
@NinaKatja 

Man könnte z.B. die Buch-Ressource verwenden. Dort kann man entweder pro Thema ein Kapitel oder ein grosses Kapitel eröffnen, wo die Videos dann hinterlegt sind. Das müsste jemand von euch mal ein wenig ausprobieren und testen mit dem Ziel zu prüfen, ob dieser Aktivitätstyp sich für die Videos eignet. Mit dem Buch kann auf jeden Fall die Gruppierung bzw. Auslagerung der Videos ähnlich wie mit dem Verzeichnis gelöst werden.

**Comment by NinaKatja** [comment]
@nelkasovic 
Das finde ich eine super Idee. Nur wie man da PDFs anhängen kann, ist mir noch unklar. Die Einheiten bestehen meist aus Video- und PDF Dokumenten. Gibt es eine elegantere Lösung oder muss ich die PDFs einzeln irgendwo im Angebot hochladen und dann im Kapitel verlinken?

**Comment by nelkasovic** [comment]
@NinaKatja 

Soviel ich weiss, kann man via Editor direkt Dateien hochladen und verwenden. Ebenfalls funktioniert eine Verlinkung mit direktem Upload bzw. fragt das System dich, ob du eine Datei hochladen, wenn du einen Link erstellen möchtest.

Weiter lassen sich Verzeichnisse auch anlegen, um z.B. PDF's zu gruppieren. Dies kannst du mit dem Gear-Icon (Zahnrad) erledigen.

**Comment by nelkasovic** [comment]
@NinaKatja Man könnte ebenfalls die PDF's in einem Verzeichnis anbieten, wie es aktuell ist und nur die Videos in ein Buch auslagern.
