### ISSUE TITLE
Videos als iframe via Textfeld eingebettet - schwierige Anwendung

### ISSUE THREAD

**Issue by angelajochum** [nelkasovic/lehr-bar.ch#7]
https://lehr-bar.ch/course/view.php?id=40#section-0

Beispiel: `<iframe src="https://tube.switch.ch/embed/KGDhobKYjL?title=hide" allow="fullscreen" allowfullscreen="" width="960" height="720" frameborder="0"></iframe></div>`

**Comment by NinaKatja** [comment]
https://lehr-bar.ch/course/view.php?id=48#section-3


![Image](https://github.com/nelkasovic/lehr-bar.ch/assets/134771252/6fa7ddca-a0aa-49eb-ad28-914c1b596ca6)


Ich weiss nicht, ob das auch hier her gehört, aber bei der Einbindung über SwitchTube (die wir ja eigentlich als Standard vorsehen), kann man nur mit den 30s Pfeilen vor und zurück springen und nicht über die "Zeitschiene", auch kann man das Videos selbst nicht lauter oder leiser stellen. Lässt sich da von deiner Seite, Nermin, noch etwas anpassen?

**Comment by nelkasovic** [comment]
@NinaKatja 

Hier sind wir durch die von SwitchTube zur Verfügung gestellten Einbettungsoptionen limitiert. Diese Seite zeigt diverse Möglichkeiten auf: https://tube.switch.ch/help/embed#js_embed. Ich konnte keine Möglichkeit für die Zeitschiene oder Lautstärkeregelung finden.
