### ISSUE TITLE
Grüner Balken gleich am Anfang eines Kurses soll entfernt werden

### ISSUE THREAD

**Issue by angelajochum** [nelkasovic/lehr-bar.ch#8]
IST:

![Image](https://user-images.githubusercontent.com/106140818/241268698-504b1c75-133e-4af9-82ba-704307c1182b.png)

SOLL:

![Image](https://user-images.githubusercontent.com/106140818/241268738-4a7c303a-2fb4-4444-bd63-48ef47241255.png)

**Comment by nelkasovic** [comment]
@angelajochum Verstehe ich es richtig, dass wir hiermit komplett auf den grünen Balken verzichten. Damit ist überall gemeint und nicht nur spezifisch an einer Stelle?

**Comment by angelajochum** [comment]
@nelkasovic 
Es geht nur um den grünen Balken am Anfang des Moduls, wird als "Allgemein" aufgezeigt .
IST:
![grafik](https://github.com/nelkasovic/lehr-bar.ch/assets/106140818/f23c0ae6-f4c7-4687-911d-9b1a38a3f58f)

Soll:
![grafik](https://github.com/nelkasovic/lehr-bar.ch/assets/106140818/52810b2d-cc14-48b7-868f-d6c681427488)

Es sind auch nicht alle Module mit diesen grünen Balken ausgestattet, sehr kurios ...
Alle anderen grünen Balken im Laufe des Moduls sollen als Kapitelüberschriften bestehen bleiben.

**Comment by angelajochum** [comment]
@nelkasovic : ich habe mich schlecht ausgedrückt. Der ganze Balken mit grün soll entfernt werden. Unter der Vorlage sieht es wie folgt aus:


![Image](https://github.com/nelkasovic/lehr-bar.ch/assets/106140818/7e4427dd-215a-49a4-a653-c5804f9da5d4)

Aus welchen Gründen auch immer, haben sich bei der Bearbeitung der Kurse auf einmal eine "Überschrift" mit dem grünen Balken ergeben. Was eigentlich nicht sein sollte.

IST (aber nicht bei allen Angeboten):



![Image](https://github.com/nelkasovic/lehr-bar.ch/assets/106140818/2d24653b-ea72-4767-9d22-c9969c4843aa)

SOLL: 



![Image](https://github.com/nelkasovic/lehr-bar.ch/assets/106140818/54b7d30c-edfa-4852-b547-4e260b824a30)


Es taucht zwar das "Bearbeiten" auf, aber es wird kein Balken aufgezeigt. So soll es wieder sein.

**Comment by angelajochum** [comment]
@nelkasovic: Konntest du den IST Zustand wieder herstellen?

**Comment by angelajochum** [comment]
@nelkasovic : bitte wieder öffnen. Der Task ist nicht ledigt.
IST:
![grafik](https://github.com/nelkasovic/lehr-bar.ch/assets/106140818/d4dc324f-6dc9-475c-889a-a222e08d8e82)


Irgendwie haben die Ersteller einen Abschnitt übergeordnet erstellt und eingefügt. Es soll aber wie in der Vorlage mit einem Textfeld "Willkommen" anfangen.
Den Abschnitt kann man nicht löschen. Der soll aber weg!!


SOLL:
![grafik](https://github.com/nelkasovic/lehr-bar.ch/assets/106140818/465a24a2-d6cb-4b39-a413-066413ae2d39)
